apiVersion: v1
kind: Service
metadata:
  name: netflix
  namespace: default
spec:
  selector:
    app: netflix
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30082
  type: NodePort
